#!/usr/bin/env python3

from sys import argv
from math import sqrt

def open_file(file_nm):
    with open(file_nm, "r", encoding="utf-8") as file:
        lines_t = file.readlines()
    number_to_factor = []
    for line_nbr in lines_t:
        number_to_factor.append(int(line_nbr))
        return number_to_factor

    def find_and_t(nbr):
        for s in range(1,nbr):
            if nbr == ((nbr // s) * s):
                print("{}={}*{}".format(nbr, (nbr // s), s))
                break


    def fact_lst(lst):

        for i in lst:
            find_and_t(i)

    if len(argv) == 2:
        fact_lst(open_read_file(argv[1]))
