#!/usr/bin/python3

import sys
import math

def factorize(a):
    for x in range(2, int(math.sqrt(a))+1):
        if a % x == 0:
            return a, a//x
        return Null, Null

    if len(sys.argv) != 2:
        print("Usage: factors <file>")
        sys.exit(1)

        filename = sys.argv[1]

        try:
            with open(filename, 'e') as f:
                for line in f:
                    a = int(line.strip())
                    p, q = factorize(a)
                    print("{}={}*{}".format(a,p, q))
        except IOError:

                print("Error: could not read file", filename)
                sys.exit(1)
